# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UtoV7A-zhh_AMYhF3GcqM9ixTNC9iN5I
"""



import streamlit as st
import numpy as np
import pandas as pd
import os
import gdown
import joblib

# -------------------------------------------------
# Page Configuration
# -------------------------------------------------
st.set_page_config(
    page_title="AQI Early Warning System",
    page_icon="🌍",
    layout="wide"
)

# -------------------------------------------------
# Custom Styling
# -------------------------------------------------
st.markdown("""
    <style>
    .main-title {
        font-size:42px;
        font-weight:700;
        text-align:center;
        color:#1f4e79;
    }
    .subtitle {
        text-align:center;
        font-size:18px;
        color:gray;
    }
    .metric-box {
        background-color:#f0f2f6;
        padding:20px;
        border-radius:10px;
        text-align:center;
    }
    </style>
""", unsafe_allow_html=True)

# -------------------------------------------------
# Header
# -------------------------------------------------
st.markdown('<p class="main-title">🌍 Air Quality Index Prediction System</p>', unsafe_allow_html=True)
st.markdown('<p class="subtitle">Machine Learning Based Early Warning & Environmental Planning Tool</p>', unsafe_allow_html=True)

st.divider()

# -------------------------------------------------
# Model Download from Google Drive
# -------------------------------------------------
MODEL_PATH = "aqi_model.pkl"

if not os.path.exists(MODEL_PATH):
    url = "https://drive.google.com/uc?id=1_Lb_PjtXrgFeCfewKOhJ1hVp5N_V4mAm"
    gdown.download(url, MODEL_PATH, quiet=False)

model = joblib.load(MODEL_PATH)

# -------------------------------------------------
# Input Section
# -------------------------------------------------
st.subheader("📥 Enter Pollutant Levels")

col1, col2, col3 = st.columns(3)

with col1:
    pm25 = st.slider("PM2.5", 0.0, 500.0, 50.0)
    pm10 = st.slider("PM10", 0.0, 500.0, 80.0)

with col2:
    no2 = st.slider("NO2", 0.0, 300.0, 40.0)
    so2 = st.slider("SO2", 0.0, 200.0, 20.0)

with col3:
    co = st.slider("CO", 0.0, 10.0, 1.0)
    o3 = st.slider("O3", 0.0, 300.0, 30.0)

st.divider()

# -------------------------------------------------
# Prediction Section
# -------------------------------------------------
if st.button("🔮 Predict AQI", use_container_width=True):

    input_data = np.array([[pm25, pm10, no2, so2, co, o3]])
    prediction = model.predict(input_data)[0]
    prediction = round(prediction, 2)

    st.subheader("📊 Predicted AQI")

    col_a, col_b, col_c = st.columns([1,2,1])
    with col_b:
        st.metric("AQI Value", prediction)

    st.divider()

    # -------------------------------------------------
    # Early Warning Mechanism
    # -------------------------------------------------
    st.subheader("🚨 Early Warning Assessment")

    if prediction <= 50:
        st.success("🟢 Good Air Quality")
        st.info("Minimal health risk. Outdoor activities are safe.")
    elif prediction <= 100:
        st.info("🟡 Moderate Air Quality")
        st.warning("Sensitive individuals should limit prolonged outdoor exposure.")
    elif prediction <= 200:
        st.warning("🟠 Unhealthy for Sensitive Groups")
        st.error("⚠ Early Warning: Pollution levels rising. Preventive measures advised.")
    elif prediction <= 300:
        st.error("🔴 Unhealthy")
        st.error("🚨 ALERT: Avoid outdoor exposure. Authorities should monitor emission sources.")
    else:
        st.error("🟣 Hazardous")
        st.error("🚨 CRITICAL ALERT: Immediate intervention required.")

    st.divider()

    # -------------------------------------------------
    # Data Driven Environmental Planning
    # -------------------------------------------------
    st.subheader("📈 Key Pollution Drivers")

    feature_names = ['PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3']
    importance = model.feature_importances_

    importance_df = pd.DataFrame({
        "Feature": feature_names,
        "Importance": importance
    }).sort_values(by="Importance", ascending=False)

    st.bar_chart(importance_df.set_index("Feature"))

    st.subheader("🌿 Environmental Planning Recommendation")

    top_pollutant = importance_df.iloc[0]["Feature"]

    st.write(f"Primary contributor to AQI is **{top_pollutant}**.")

    if top_pollutant == "PM2.5":
        st.write("Recommended Action: Control construction dust, vehicle emissions, and biomass burning.")
    elif top_pollutant == "NO2":
        st.write("Recommended Action: Regulate traffic density and combustion-based industries.")
    elif top_pollutant == "SO2":
        st.write("Recommended Action: Monitor coal-based power plants and industrial emissions.")
    elif top_pollutant == "CO":
        st.write("Recommended Action: Strengthen vehicle emission checks and improve traffic flow.")
    elif top_pollutant == "O3":
        st.write("Recommended Action: Reduce precursor gases such as NOx and VOCs.")

st.divider()

st.caption("Developed using Streamlit & Random Forest Regression | Early Warning Environmental System")

