# -*- coding: utf-8 -*-
"""aqi deploy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LDS6Mj3jSPRTp0S7tqraAE7z3osU9PS
"""




import streamlit as st
import numpy as np
import joblib
import pandas as pd
import matplotlib.pyplot as plt

# ---------------------------------------------------
# Page Configuration
# ---------------------------------------------------
st.set_page_config(
    page_title="Smart AQI Monitoring System",
    page_icon="🌍",
    layout="wide"
)

# ---------------------------------------------------
# Load Model
# ---------------------------------------------------
model = joblib.load("aqi_xgboost_model.pkl")

# ---------------------------------------------------
# Header
# ---------------------------------------------------
st.title("🌍 Smart Air Quality Monitoring & Early Warning System")
st.markdown("AI-powered AQI prediction with health advisory and environmental planning insights.")

st.markdown("---")

# ---------------------------------------------------
# Sidebar Inputs
# ---------------------------------------------------
st.sidebar.header("Enter Pollutant Concentrations")

pm25 = st.sidebar.number_input("PM2.5", min_value=0.0, value=50.0)
pm10 = st.sidebar.number_input("PM10", min_value=0.0, value=80.0)
no = st.sidebar.number_input("NO", min_value=0.0, value=20.0)
no2 = st.sidebar.number_input("NO2", min_value=0.0, value=30.0)
nox = st.sidebar.number_input("NOx", min_value=0.0, value=40.0)
co = st.sidebar.number_input("CO", min_value=0.0, value=1.0)
o3 = st.sidebar.number_input("O3", min_value=0.0, value=25.0)

# ---------------------------------------------------
# Early Warning System
# ---------------------------------------------------
def early_warning_system(aqi):

    if aqi <= 50:
        return "Good", "Air quality is safe.", "Maintain green policies."
    elif aqi <= 100:
        return "Satisfactory", "Sensitive individuals reduce outdoor exposure.", "Encourage public transport."
    elif aqi <= 200:
        return "Moderate", "Breathing discomfort for sensitive groups.", "Control traffic & construction dust."
    elif aqi <= 300:
        return "Poor", "Respiratory discomfort likely.", "Restrict high-emission industries."
    elif aqi <= 400:
        return "Very Poor", "High health alert.", "Temporary emission restrictions required."
    else:
        return "Severe", "Emergency health warning.", "Activate pollution emergency protocol."

# ---------------------------------------------------
# Prediction Section
# ---------------------------------------------------
if st.button("Predict AQI"):

    input_data = np.array([[pm25, pm10, no, no2, nox, co, o3]])
    prediction = model.predict(input_data)[0]
    category, health_msg, policy_msg = early_warning_system(prediction)

    # ---------------------------------------------------
    # KPI Section
    # ---------------------------------------------------
    col1, col2 = st.columns(2)

    with col1:
        st.metric("Predicted AQI", round(prediction, 2))

    with col2:
        st.metric("Air Quality Status", category)

    # ---------------------------------------------------
    # AQI Risk Meter
    # ---------------------------------------------------
    st.subheader("AQI Risk Level")
    risk_percentage = float(prediction) / 500
    risk_percentage = max(0.0, min(risk_percentage, 1.0))

    st.progress(risk_percentage)
    st.caption(f"Risk Level: {round(risk_percentage*100, 1)}%")



    # ---------------------------------------------------
    # Health & Policy
    # ---------------------------------------------------
    st.markdown("### 🚑 Health Advisory")
    st.warning(health_msg)

    st.markdown("### 🏛 Environmental Planning Recommendation")
    st.success(policy_msg)

    st.markdown("---")

    # ---------------------------------------------------
    # Pollutant Visualization
    # ---------------------------------------------------
    st.subheader("Pollutant Concentration Overview")

    pollutant_data = pd.DataFrame({
        "Pollutant": ["PM2.5", "PM10", "NO", "NO2", "NOx", "CO", "O3"],
        "Value": [pm25, pm10, no, no2, nox, co, o3]
    })

    fig1, ax1 = plt.subplots()
    ax1.bar(pollutant_data["Pollutant"], pollutant_data["Value"])
    ax1.set_ylabel("Concentration")
    ax1.set_title("Pollutant Levels")
    st.pyplot(fig1)

    st.markdown("---")

    # ---------------------------------------------------
    # Feature Importance
    # ---------------------------------------------------
    st.subheader("Model Feature Importance")

    try:
        feature_names = ["PM2.5", "PM10", "NO", "NO2", "NOx", "CO", "O3"]
        importances = model.feature_importances_

        importance_df = pd.DataFrame({
            "Feature": feature_names,
            "Importance": importances
        }).sort_values(by="Importance", ascending=True)

        fig2, ax2 = plt.subplots()
        ax2.barh(importance_df["Feature"], importance_df["Importance"])
        ax2.set_xlabel("Importance Score")
        ax2.set_title("Feature Contribution to AQI")
        st.pyplot(fig2)

    except:
        st.info("Feature importance not available.")

